### ISSUE TITLE
Add fork_database unittests to cover best fork choice rules

### ISSUE THREAD

**Issue by heifner** [AntelopeIO/spring#10]
Depends on AntelopeIO/leap#2125 

AntelopeIO/leap#2125 Did not add test coverage for `fork_database` best fork choice rules. 
Add unittest coverage of fork choices with multiple branches and scenarios.

**Comment by arhag** [comment]
Create Savanna versions of the following tests from https://github.com/AntelopeIO/spring/issues/196:
- forking
- prune_remove_branch
- irreversible_mode
- push_block_returns_forked_transactions

Also consider any tests needed to exercise any code paths that are not currently being exercised by the new fork choice rule implementation.
