### ISSUE TITLE
Remove `kv_database_config` from `snapshot_global_property_object`

### ISSUE THREAD

**Issue by linh2931** [AntelopeIO/spring#102]
https://github.com/AntelopeIO/spring/issues/77 calls for removing `kv_database_config` from the `global_property_object` and from the snapshot. It was only removed from `global_property_object` but not from `snapshot_global_property_object` by PR https://github.com/AntelopeIO/spring/pull/99.  Removal from `snapshot_global_property_object` should be done separately as additional work is required to make sure old snapshots can be loaded.

**Comment by heifner** [comment]
Looks like it was removed: https://github.com/AntelopeIO/spring/pull/99/files#diff-60e9aa15db2886d950de829a0a602fe29fe4e69f28621e45be60e46a51c096a5L75

**Comment by linh2931** [comment]
> Looks like it was removed: https://github.com/AntelopeIO/spring/pull/99/files#diff-60e9aa15db2886d950de829a0a602fe29fe4e69f28621e45be60e46a51c096a5L75

Thanks. It was removed from `global_property_object` but not  from `snapshot_global_property_object`. I changed the title.

**Comment by ericpassmore** [comment]
Note:start
group: IF
category: INTERNALS
summary: Improve set_proposed_finalizers, no longer has side-effects if transaction fails.
Note:end
