### ISSUE TITLE
Invalid warn message on startup

### ISSUE THREAD

**Issue by heifner** [AntelopeIO/spring#1052]
```
warn  2024-12-05T13:45:22.176 nodeos    producer_plugin.cpp:1617      plugin_startup       ] Legacy consensus active. Accepting speculative transaction execution not recommended in read-mode=irreversible
```

Savanna was active at startup. The following is not returning the root of the fork db.
https://github.com/AntelopeIO/spring/blob/631fed0498bb87d7eba266aa1552f4d4bf95e0e2/plugins/producer_plugin/producer_plugin.cpp#L1594-L1595

**Comment by bhazzard** [comment]
Test to confirm this is a bug in 1.0, otherwise, we'll change milestone to 1.1
