### ISSUE TITLE
Failing restarts -> unclean shutdown: replay required

### ISSUE THREAD

**Issue by jakobilobi** [AntelopeIO/spring#1069]
Hey people,

I'm new to running stuff on the EOS Network and I'm having some issue with my `nodeos` client ending up in a dirty database state after restarts fail, hoping to find some advice! The relevant log messages are:

```
info  2024-12-16T09:08:10.150 nodeos    account_query_db.cpp:143      build_account_query_ ] Building account query DB
...
# process killed due to timeout
...
error 2024-12-16T09:09:45.305 nodeos    main.cpp:220     main    ] database dirty flag set (likely due to unclean shutdown): replay required
```

I've done an attempt at searching various platforms for answers and recommendations but haven't found anything conclusive. What I have done for my node is to increase the timeout for restarts for the service running the node, which should make it restart more safely, but I do have some questions:

- With the state of chain height ~410M, what is an expected shutdown time for a `nodeos` client running on an average machine? E.g. for the `Building account query DB` step, which seems to be the bottleneck.
- Are there ways of configuring the node to continually save the state to disk, to allow quicker (and hopefully safer) restarts?
- When I replay (`--replay-blockchain`) after a dirty database error, I'm using the original snapshot `.bin` I have on the node. This one is 10M blocks old (we need the block and state history for these blocks), which makes the replay take 12-14 hours. Can I use a newer snapshot, to make the process faster, without losing the block and state history data?

If I'm in the wrong place with these questions (couldn't find a better place) please let me know where I should take them :)

Cheers

**Comment by heifner** [comment]
- A number of improvements to shutdown time have been included in the recent patch releases (and more coming). Make sure you are running 1.0.3.
- Building the account query DB does take some time on startup. If you can disable the account query DB if you are not using it.
- For fastest start/stop of a node, the default `database-map-mode` of `mapped` is recommended. Running in this mode it is recommended to have 256 GB of RAM. The default `mapped` mode does continually save state to disk and will shutdown/start the fastest of the `database-map-mode` options.
- You can use any snapshot that is before your current state history location. It will start from the snapshot and start filling in state history when it catches up.

**Comment by jakobilobi** [comment]
Thanks a lot for your recommendations!

Running 1.0.3 :white_check_mark:

So for the build of the account query DB, maybe my node is behaving out of the norm but the build runs on shutdown and not startup. Log looks like this upon shutdown:

```
systemd[1]: Stopping EOS Node Client...
nodeos[1959034]: info  2024-12-18T14:04:51.500 nodeos    main.cpp:172                  operator()           ] appbase quit called
nodeos[1959034]: info  2024-12-18T14:04:51.501 nodeos    controller.cpp:1829           operator()           ] 5768 reversible blocks replayed
nodeos[1959034]: info  2024-12-18T14:04:51.509 nodeos    controller.cpp:1880           startup              ] Finished initialization from snapshot (snapshot load time was 3721s)
nodeos[1959034]: info  2024-12-18T14:04:51.538 nodeos    chain_plugin.cpp:1138         plugin_startup       ] starting chain in read/write mode
nodeos[1959034]: info  2024-12-18T14:04:51.538 nodeos    chain_plugin.cpp:1146         plugin_startup       ] Blockchain started; head block is #410107312
nodeos[1959034]: info  2024-12-18T14:04:51.539 nodeos    account_query_db.cpp:143      build_account_query_ ] Building account query DB
nodeos[1959034]: info  2024-12-18T14:20:29.203 nodeos    account_query_db.cpp:163      build_account_query_ ] Finished building account query DB in 937.66470300000003135
nodeos[1959034]: info  2024-12-18T14:20:29.219 nodeos    block_handle.cpp:21           write                ] Writing chain_head block 410107312
```

Speculations here but could it perhaps be that the node hasn't completely finished starting up when I try to reboot it (this was quite close in time after starting it, just a few minutes), so these steps remaining in the startup sequence try to run before it completes shutdown?

> You can disable the account query DB if you are not using it.

I only found one `nodeos` setting mentioning "account queries", does it control both enabling of the queries themselves as well as the account query DB?

```
  --enable-account-queries arg (=0)     enable queries to find accounts by 
                                        various metadata.
```

We're using the node for Hyperion indexing and as I understand it the account queries should be enabled for that. So if the DB is a requirement for the queries, we'll simply have to adapt.

**Comment by heifner** [comment]
See my `[]` comments below. In short, the node has not finished startup when it was told to shutdown.

```
systemd[1]: Stopping EOS Node Client...
nodeos[1959034]: info  2024-12-18T14:04:51.500 nodeos    main.cpp:172                  operator()           ] appbase quit called
[nodeos received a signal to quit, but it is still starting up]
nodeos[1959034]: info  2024-12-18T14:04:51.501 nodeos    controller.cpp:1829           operator()           ] 5768 reversible blocks replayed
nodeos[1959034]: info  2024-12-18T14:04:51.509 nodeos    controller.cpp:1880           startup              ] Finished initialization from snapshot (snapshot load time was 3721s)
[nodoes finished loading snapshot]
nodeos[1959034]: info  2024-12-18T14:04:51.538 nodeos    chain_plugin.cpp:1138         plugin_startup       ] starting chain in read/write mode
[nodeos still starting up, has not processed the shutdown signal yet]
nodeos[1959034]: info  2024-12-18T14:04:51.538 nodeos    chain_plugin.cpp:1146         plugin_startup       ] Blockchain started; head block is #410107312
nodeos[1959034]: info  2024-12-18T14:04:51.539 nodeos    account_query_db.cpp:143      build_account_query_ ] Building account query DB
[nodeos still starting up, has not processed the shutdown signal yet]
nodeos[1959034]: info  2024-12-18T14:20:29.203 nodeos    account_query_db.cpp:163      build_account_query_ ] Finished building account query DB in 937.66470300000003135
[Done with startup. Processes shutdown signal and starts to shutdown.]
nodeos[1959034]: info  2024-12-18T14:20:29.219 nodeos    block_handle.cpp:21           write                ] Writing chain_head block 410107312
```

If account query is needed for Hyperion then yes you need the `--enable-account-queries` which enables both the account query db and along with `--plugin eosio::chain_api_plugin` enables the account query RPC endpoint.

**Comment by jakobilobi** [comment]
Alright, makes sense.

Thanks again, you've been very helpful :ok_hand:
