### ISSUE TITLE
Create IF versions of applicable unittests

### ISSUE THREAD

**Issue by heifner** [AntelopeIO/spring#11]
- protocol_feature_tests.cpp
- restart_chain_tests.cpp
- block_tests.cpp
- chain_tests.cpp
- database_tests.cpp
- forked_tests.cpp

Consider if other tests that IF should make no difference if they should only be run in IF mode.
For example: dry_run_trx_tests.cpp, eosio.system_tests.cpp, etc.

**Comment by arhag** [comment]
For the DeepMind test, we can keep it as one test with one log. And we should activate the IF hardfork at the beginning. But we should do what exists in the current test before transitioning to Savanna. Then we extend the test to transition to Savanna, update the proposer schedule, and produce some blocks.

**Comment by linh2931** [comment]
### Summary
#### Tests Updated
`api_tests.cpp, auth_tests.cpp, block_tests.cpp, chain_tests.cpp, database_tests.cpp, dry_run_trx_tests.cpp, eosio.token_tests.cpp, misc_tests.cpp, payloadless_tests.cpp, protocol_feature_tests.cpp, read_only_trx_tests.cpp, restart_chain_tests.cpp, snapshot_tests.cpp, special_accounts_tests.cpp, wasm_tests.cpp
`
#### Tests in PR
`eosio.system_tests.cpp, ram_tests.cpp, wasm_config_tests.cpp`

#### Tests in progress
`currency_tests.cpp`

#### Tests Failed
`partitioned_block_log_tests.cpp, state_history_tests.cpp`

#### Tests To Do
`deep_mind_tests.cpp, forked_tests.cpp, whitelist_blacklist_tests.cpp`

#### The rest are not applicable (Already Savanna specific or not using libtester)

**Comment by arhag** [comment]
Tests that still need to be individually addressed are tracked by separated issues.
