### ISSUE TITLE
Test Failure: svnn_ibc_unit_test_eos-vm-jit

### ISSUE THREAD

**Issue by linh2931** [AntelopeIO/spring#139]
https://github.com/AntelopeIO/spring/actions/runs/9084138059/job/24964976733?pr=133#step:5:1356

**Comment by heifner** [comment]
https://github.com/AntelopeIO/spring/actions/runs/9100452880/job/25015946844

**Comment by spoonincode** [comment]
https://github.com/AntelopeIO/spring/actions/runs/9117083532/job/25067616041

```
10 assert_exception: Assert Exception
retrys: Never saw this nodes vote processed before timeout
    {}
    unit_test  tester.cpp:515 _wait_for_vote_if_needed
rethrow
    {}
    unit_test  svnn_ibc_tests.cpp:379 test_method

unknown location(0): fatal error: in "svnn_ibc/ibc_test": std::runtime_error: Caught Unexpected Exception
/__w/spring/spring/unittests/svnn_ibc_tests.cpp(228): last checkpoint
```

note: this branch was only up to date with 72b1e72 at the time of the failure
