### ISSUE TITLE
[Jungle Slownet] Problems Syncing From Peers

### ISSUE THREAD

**Issue by ericpassmore** [AntelopeIO/spring#141]
ESO USA encountering problems syncing. Stops syncing with message, `old state lib catchup becoming head catchup` . Restarting nodeos, get the syncing unstuck. Running `release/1.0-beta1`. Also reported syncing stops and remote is closing p2p connections. 

![telegram-cloud-photo-size-1-5053234714479012888-y](https://github.com/AntelopeIO/spring/assets/6685407/6a227dc2-5f1f-45bf-adef-846bc66c2b69)

**Comment by heifner** [comment]
Able to reproduce. Aggravated by `sync-fetch-span = 200`.
