### ISSUE TITLE
Reading Leap ship data

### ISSUE THREAD

**Issue by cc32d9** [AntelopeIO/spring#171]
The Spring node should either be able to read the Leap state history directly, or there needs to be a utility to decompress it.

**Comment by cc32d9** [comment]
also, what happens to the ship archive continuity if the node is upgraded to Spring?

**Comment by spoonincode** [comment]
log format hasn't changed from Leap4 through Spring1; you can even write to the logs in Spring1 and then use those logs in Leap4 or Leap5.
