### ISSUE TITLE
Implement `controller::replace_producer_keys` for Savanna

### ISSUE THREAD

**Issue by linh2931** [AntelopeIO/spring#207]
`replace_producer_keys` has not been implemented yet.

https://github.com/AntelopeIO/spring/blob/2b86741f176a984a662d6ff57423b6dfc45904f6/libraries/chain/controller.cpp#L1041

**Comment by heifner** [comment]
I think it would be useful to add a `spring-util`  `chain` action that uses `replace_producer_keys` to easily setup a local testnet.
