### ISSUE TITLE
ship refactor followup: batch blocks for sending

### ISSUE THREAD

**Issue by spoonincode** [AntelopeIO/spring#223]
Currently ship operates by deciding what block to send on the main thread, jumping to the ship thread to actually send that block, and then jumping back to the main thread again to decide what block to send, repeat.

It should be quite straightforward to instead of deciding what _block_ to send, decide what _blocks_ to send (up to some reasonable limit). Batching in this manner will reduce the frequency of taking the round trip to the separate ship thread when a ship client is in catchup.

**Comment by bhazzard** [comment]
In absence of a way to monitor the potential performance impact of this change, we'll opt not to tackle this at this time.
