### ISSUE TITLE
ship abi.cpp's `finality_data` doesn't match up with `finality_data_t`

### ISSUE THREAD

**Issue by spoonincode** [AntelopeIO/spring#243]
https://github.com/AntelopeIO/spring/blob/8f65101b071768e8f213cd62e1a580f55aed882b/libraries/chain/include/eosio/chain/block_state.hpp#L61-L69
vs
https://github.com/AntelopeIO/spring/blob/8f65101b071768e8f213cd62e1a580f55aed882b/libraries/state_history/abi.cpp#L576-L582

**Comment by greg7mdp** [comment]
That was missed in https://github.com/AntelopeIO/spring/pull/124 and https://github.com/AntelopeIO/spring/pull/220.
