### ISSUE TITLE
Test failure: libtester tests exit code 143

### ISSUE THREAD

**Issue by heifner** [AntelopeIO/spring#254]
https://github.com/AntelopeIO/spring/actions/runs/9418036499/job/25946161128

**Comment by linh2931** [comment]
This is due to eosio_system_unit_test taking too long. I am going to split it.

**Comment by linh2931** [comment]
It happened here too https://github.com/AntelopeIO/spring/actions/runs/9372817111/job/25806046583?pr=236#step:16:984

**Comment by heifner** [comment]
https://github.com/AntelopeIO/spring/actions/runs/9421173861/job/25955525474?pr=258
