### ISSUE TITLE
deepmind decoding issue of finality_data in ACCEPTED_BLOCK_V2

### ISSUE THREAD

**Issue by fschoell** [AntelopeIO/spring#263]
I'm currently testing decoding the finality_data field within the ACCEPTED_BLOCK_V2, but I'm getting this issue:

`
Jun 10 15:27:06 spring1-sfdm41 nodeos[201305]: ACCEPTED_BLOCK_V2: unable to decode finality data: unmarshalling binary finality data: checksum 256 required [32] bytes, remaining [28] (line "ACCEPTED_BLOCK_V2 3435268 3423055 e2a7d15bc0a6bb15abab5ac5000000346b03723df8066af391b2d9f9e507ea35aa2f32f73a24eab8c813af29aaa600000000000000000000000000000000000000000000000000000000000000006481f63dbfdaef74fe7606b6009434a82f5c57c4e20b1ef45abed1358463f794000000800001020007026b3400010000002008bb2bb9e760a9a00c0c7900812d276372d71813b472eb6c7cc067a2278730403fd8a39d88ebcf5fd7f9d8f1ddfa3ee6672345718298e54646a66a499204db8300010300cc01026b34000115ffff1f00c001945c594481744eba58dadbbda21dbd3575179147de53dce0dfdf4ef18ca61ed396f8553dce807dae62ef465e55829503e4b68126ffa05e4f31cad986ef392a87b552fd9dde7d757f47112ea01118271547defad5228bd70cd4a4cd1482ad17117b25596749a0c8d620db888929f53b22e702bc3c51d8bb0fbb29560b3945cb29916807654b2b789b3da7fc9b2434a205f540fd39b1dd53af7de7f18ddea7811a999cc48985592aedba335c5638d7d9e748ad13f9b1b65b760556ad84ae2ab709 01000000000000000100000050f3c0f34771e2f2b8fcd27547f21fba504fa64708222d41336af632c19b1a887ab43c9132eb17408027d834d2c51e44fd4d51d82a09123f8a728c8a65109872")
`

Added a test case that shows the decoding in here: https://github.com/pinax-network/firehose-antelope/blob/feature/spring/codec/antelope/spring_v1/types_test.go

The finality data I'm getting from that deep mind log seems a bit short to be decoded into the finality data struct ([this](https://github.com/pinax-network/firehose-antelope/blob/f4c088afdc7c9d4ed8d6ac14989df85d1e436be2/codec/antelope/spring_v1/types.go#L49-L69) is the one I'm decoding into). From my understanding this should be:

```
01000000 -> uint32 major_version
00000000 -> uint32 minor_version
01000000 -> uint32 active_finalizer_policy_generation
50f3c0f3 -> uint32 final_on_strong_qc_block_num
4771e2f2b8fcd27547f21fba504fa64708222d41336af632c19b1a887ab43c91 -> sha256 action_mroot
32eb17408027d834d2c51e44fd4d51d82a09123f8a728c8a65109872 -> sha256 base_digest (short of 4 bytes)
-> missing proposed_finalizer_policy or empty flag
````

**Comment by heifner** [comment]
What commit hash is your nodeos?

**Comment by fschoell** [comment]
```
$ nodeos --full-version
info  2024-06-10T18:10:24.811 nodeos    main.cpp:151                  main                 ] nodeos started
v1.0.0-beta1.2-32820cf55daabc28116ac0771c829e223a1f0929-dirty
```

**Comment by fschoell** [comment]
that node was accidentally updated to the beta2 and then downgraded again. Not sure if this could have caused any issues. Just in case I replayed from a snapshot but the problem appeared again.

**Comment by heifner** [comment]
Please test on the beta2 testnet as beta1 testnet (v1.0.0-beta1.2) has an old definition for `finality_data_t`.

**Comment by fschoell** [comment]
working on the Spring beta2 testnet
