### ISSUE TITLE
Test failure: lib_advance_if_test

### ISSUE THREAD

**Issue by heifner** [AntelopeIO/spring#302]
https://github.com/AntelopeIO/spring/actions/runs/9547360011/job/26312762056

```
Traceback (most recent call last):
  File "/__w/spring/spring/build/tests/lib_advance_test.py", line 102, in <module>
    assert prodA.waitForNextBlock(timeout=6), "Production node A should continue to advance, even after bridge node is killed"
AssertionError: Production node A should continue to advance, even after bridge node is killed
```

**Comment by heifner** [comment]
Producer D (node03) did not send out its produced block to bridge node because `peer_syncing_from_us` was true. It did come out of peer syncing with us but only right after the 6 block timeout.

**Comment by linh2931** [comment]
https://github.com/AntelopeIO/spring/actions/runs/9654126075/job/26628097702#step:4:1046

```
File "/__w/spring/spring/build/tests/lib_advance_test.py", line 102, in <module>
    assert prodA.waitForNextBlock(timeout=6), "Production node A should continue to advance, even after bridge node is killed"
```

**Comment by heifner** [comment]
> https://github.com/AntelopeIO/spring/actions/runs/9654126075/job/26628097702#step:4:1046
> 
> ```
> File "/__w/spring/spring/build/tests/lib_advance_test.py", line 102, in <module>
>     assert prodA.waitForNextBlock(timeout=6), "Production node A should continue to advance, even after bridge node is killed"
> ```

Did not have the fix merged to `main` yet.
