### ISSUE TITLE
Fork choice rule: determine whether we should use `last_qc_block_num` or `last_qc_block_timestamp`.

### ISSUE THREAD

**Issue by greg7mdp** [AntelopeIO/spring#330]
Currently, we  use `last_qc_block_num`  as the third criteria in our fork choice rule:

https://github.com/AntelopeIO/spring/blob/a9e4dcfbca2464a255fc453341034df48d193554/libraries/chain/fork_database.cpp#L91-L99

Determine whether we should use `last_qc_block_timestamp` instead.

**Comment by arhag** [comment]
We should also use `last_final_block_timestamp`.
