### ISSUE TITLE
Provide full finalizer/proposer policy (not diff) in deep-mind logs

### ISSUE THREAD

**Issue by arhag** [AntelopeIO/spring#343]
When a new finalizer policy or proposer policy is proposed in a block, the deep-mind logs should contain an entry associated with the block that contains the full policy (not just the diff). The keys within these policies should have string encoding.

We should also always include in the deep-mind logs for each block the active proposer policy (with version within) and active finalizer policy (with generation within). These policies should also be represented in their full form with string encoding of keys as well.

**Comment by fschoell** [comment]
I think it would make sense to reintroduce a block_state again, similar to the `block_state_legacy` in  the old `ACCEPTED_BLOCK` log. Ideally the new block_state should also contain all fields from the legacy state that could still be relevant. 

After doing some testing on the Spring testnet it seems like it's not straightforward to backport the new features to dfuse. Eosq, for example, depends on the active_schedule being set on each block, which was available before but isn't anymore. From my understanding it's possible to receive this from the header extensions but it's only available for schedule changes, which makes it more difficult to extract.
