### ISSUE TITLE
Support database mode locked 

### ISSUE THREAD

**Issue by ericpassmore** [AntelopeIO/spring#349]
In Spring when starting a new node from genesis with option `--database-map-mode locked` getting the following error:
```
[Thread 0x7f9bf2b8d640 (LWP 1698) exited]
error 2024-07-10T17:45:36.151 nodeos    main.cpp:217                  main                 ] 13 N5boost10wrapexceptISt13runtime_errorEE: unable to find index for eosio::chain::database_header_object in read only database
rethrow unable to find index for eosio::chain::database_header_object in read only database: 
    {"what":"unable to find index for eosio::chain::database_header_object in read only database"}
    nodeos  chain_plugin.cpp:1097 plugin_initialize

[Inferior 1 (process 1694) exited with code 0376]
```
[locked-db-error-logs.txt](https://github.com/user-attachments/files/16167099/locked-db-error-logs.txt)

**Comment by linh2931** [comment]
From @spoonincode:  _if you're not running as root (and of course you ought not to), ulimit -l needs to be high enough_

I verified that with a default `8,172,232` KB locked memory limit on my machine, I could start `nodeos` with database mode locked successfully. But after I reduced the limit by `ulimit -l 81,723`, I got the same error of `Failed to mlock database`. Please increase the locked memory limit.

**Comment by linh2931** [comment]
Add better error message when failed to mlock database, including the locked memory limit at the moment.
