### ISSUE TITLE
Unable to access data in the trace_api plugin

### ISSUE THREAD

**Issue by aaroncox** [AntelopeIO/spring#352]
Currently we are unable to get some trace information out of the trace_api plugin.

We have confirmed this works in Leap 5.0.1, but the data is coming back incorrectly when using Spring.

For context, this is the patch we apply to nodeos in order to modify the results and get all the data we need (which isn’t by default included in the trace_api). 

https://gist.github.com/aaroncox/84b088d4c8946e8d8ded4f4cdabbcd45

I applied this patch to both a Leap v5.0.1 node as well as to Spring master node. 

I launched both of these nodes on Jungle 4, then I queried both of them at block 149699965, and it appears as if there’s a number of fields who’s data is empty or going to their default values. 

This screenshot of the JSON compare shows Leap v5.0.1 on the left and Spring on the right.

![telegram-cloud-photo-size-1-4934011567712873830-y](https://github.com/AntelopeIO/spring/assets/677686/7697c695-4590-48f9-ace0-01a229006a56)

Things like the `receipt_receiver` return properly on Leap version as "eosio", but return an empty value from Spring.

Here's a full JSON diff of the results: 

https://jsoncompare.com/#!/diff/id=b6bcdd6926828c67cc2fd057d1b87fbf/

I'm not sure what changed exactly - or if we need to modify our code to somehow access that data differently, but this patch has been how we retrieve this data since the v2.x days.

The related telegram discussion starts here: https://t.me/c/2108384926/1099

**Comment by heifner** [comment]
Is it only certain blocks are all blocks? I just tried this with EOS Mainnet block 325843000 with no issue.

**Comment by heifner** [comment]
Maybe an issue with how the diff was applied. It did not apply cleanly for me. Do you have a branch I can test?

**Comment by aaroncox** [comment]
All blocks as far as I know. I tried replaying Jungle4 from block 1 and hit the error on the first block, so then tried a few random heights, one of which was what I shared above.

For the patch, I may have shared the one for Leap 5 instead of Spring on accident. I've updated the gist to now be a patch that applies properly to `spring/main`, which is at the same link here:

https://gist.github.com/aaroncox/84b088d4c8946e8d8ded4f4cdabbcd45

**Comment by heifner** [comment]
You are missing the `FC_REFLECT` in `trace.hpp` in the gist now. It was there for the Leap 5.0 version. If you add in the `FC_REFLECT` it fixes the problem:
```
FC_REFLECT(eosio::trace_api::action_trace_v0, (action_ordinal)(creator_action_ordinal)(closest_unnotified_ancestor_action_ordinal)(receipt_receiver)(global_sequence)(recv_sequence)(auth_sequence)(code_sequence)(abi_sequence)(receiver)(account)(action)(authorization)(data)(context_free)(elapsed)(account_ram_deltas))

```

**Comment by aaroncox** [comment]
Thank you, I'm not sure how I missed that 🤦 

Classic PEBKAC!
