### ISSUE TITLE
Test Failure: performance_test_basic_read_only_trxs 

### ISSUE THREAD

**Issue by linh2931** [AntelopeIO/spring#358]
This is the first time I see this failure:

https://github.com/AntelopeIO/spring/actions/runs/9896737400/job/27340099533#step:4:2208

**Comment by heifner** [comment]
There are no logs in the tar file. See #360.

**Comment by arhag** [comment]
Closed because there is nothing to do with this for now. We can open another issue if this happens again and because of #360 we will have logs to work with.
