### ISSUE TITLE
Investigate spring testnet 2 LIB pause

### ISSUE THREAD

**Issue by heifner** [AntelopeIO/spring#417]

**Comment by heifner** [comment]
- LIB stopped because block producers stopped getting votes from finalizers: funnyhamster, gorillapower, hippopotamus, eosnationftw, bighornsheep, clevermonkey, hungryolddog. Since not enough finalizers were voting to reach quorum, finality (LIB) did not advance.
- When finality (LIB) does not advance the fork database (which is held in memory) grows unbounded. Nodes began to die when they ran out of memory/swap.
- A quorum of votes were shortly able to be achieved again the next morning but because the voting was on old blocks they were never able to advance finality before the finalizer node died due to running out of memory.
  - The next beta (beta4) will mitigate against this by only voting on recent votes.

**Comment by greg7mdp** [comment]
> The next beta (beta4) will mitigate against this by only voting on recent votes.

How will not voting on older blocks prevent the fork_db growth?

**Comment by heifner** [comment]
> > The next beta (beta4) will mitigate against this by only voting on recent votes.
> 
> How will not voting on older blocks prevent the fork_db growth?

It would be able to much quicker pass over old blocks and vote on newer ones. Or course, it would still need to avoid running out memory by using a large swap.
