### ISSUE TITLE
Verify dual finalizers in active and pending finalizer policies vote in the same way in received QCs

### ISSUE THREAD

**Issue by linh2931** [AntelopeIO/spring#467]
For a received QC, if a finalizer is in both active finalizer policy and pending finalizer policy (_**dual finalizer**_), verify the finalizer votes in the same way on both policies or not vote at all.

**Comment by greg7mdp** [comment]
Is this needed? The finalizer votes only once on each block, and the vote is added to either one or two qcs depending on whether a pending policy is active. So unless the nodeos code is maliciously modified the issue would not occur.

Also, what should we do if that were to happen? Disregard the QC entirely? This would allow a single faulty finalizer to prevent the chain from finalizing.

**Comment by linh2931** [comment]
Yes, this is to protect against malicious actors (who can even modify nodes code) in the same way we verify other parts of incoming QCs. We talked about this in the final hour of this Wednesday meeting.

@heifner @arhag

**Comment by heifner** [comment]
Yes, we should disregard the QC entirely and also the block it came in on. This can only happen by a misbehaving producer. We should not validate that block or the QC from that producer.
