### ISSUE TITLE
Verify BLS key for producer is configured in config.ini

### ISSUE THREAD

**Issue by heifner** [AntelopeIO/spring#488]
If not configured then do not allow the producer to start.

- If `producer-name` configured
  - If active finalizer policy does not exist then just verify any BLS key is configured
  - If active finalizer policy exists then verify BLS key matches

Cons: 
- Prevents separation of finalizer and block producer nodeos.

**Comment by ericpassmore** [comment]
This would need to happen after the hard fork, after the BLS protocol features and after application of the new system contracts. This would apply to restarts after a critical point, and therefore may not be helpful.

**Comment by heifner** [comment]
> This would need to happen after the hard fork, after the BLS protocol features and after application of the new system contracts. This would apply to restarts after a critical point, and therefore may not be helpful.

It is a bit of a pain for BPs, but we could verify that the BLS key is there, but not verify it is the correct one. That would require creating the BLS key before upgrading to Spring 1.0.

**Comment by matthewdarwin** [comment]
This feature, if implemented, should removed post 1.0.

**Comment by arhag** [comment]
This limits the ability of finalizers to have backup nodes with different finalizer keys that can be switched to as the active one.
