### ISSUE TITLE
`PerformanceHarness` version roll back ambiguity

### ISSUE THREAD

**Issue by spoonincode** [AntelopeIO/spring#49]
`PerformanceHarness` configures itself differently based on what `nodeos --full-version` returns. Its behavior is altered if the version begins with `v2` or `v4` with the assumption if it's not one of those versions it must be the "latest". So for spring v1 this code still does what is expected ("latest"), but spring v2 will not follow the expected path. Examples,
https://github.com/AntelopeIO/spring/blob/bef48a2287f3cff0421f09b40cc4a7bae48317d9/tests/PerformanceHarness/performance_test_basic.py#L128-L131
https://github.com/AntelopeIO/spring/blob/bef48a2287f3cff0421f09b40cc4a7bae48317d9/tests/PerformanceHarness/performance_test_basic.py#L144-L147

**Comment by bhazzard** [comment]
For now let's remove this code handling of versions.

We only care about performance relative to the previous major version. One way to do that is to run the performance harness independently on each major version. If the new performance harness has changes to tests / metrics that aren't backported, that approach won't work. In that case we may need to reintroduce only for the previous supported version.

Similar issue: #48
