### ISSUE TITLE
Consider enabling vote propogation by default in 1.0

### ISSUE THREAD

**Issue by matthewdarwin** [AntelopeIO/spring#490]
To help ensuring the network is stable on consensus activation, consider enabling vote propagation by default in 1.0. This of course creates load on nodes that don't need voting.  

The current default is really correct, but this is a request to consider making it incorrect in the interest of network stability on feature launch.
The default can be changed back in a future release.

**Comment by arhag** [comment]
We plan to go with https://github.com/AntelopeIO/spring/issues/495 as a medium-term protection instead.
