### ISSUE TITLE
Build tooling to test vote propogation prior to savana feature activation

### ISSUE THREAD

**Issue by matthewdarwin** [AntelopeIO/spring#491]
spring 1.0 will propogate votes through the network without savana features being activated.

To ensure the network is ready for feature activation, build a tool and provide instructions for using to allow node operators to see if they would receive votes.

eg
-  a temporary one-off-test-tool like "generate-fake-vote.exe from bp fake1234"
- something you can see on the nodes side (prometheus, log entry, etc) where you can see that you got votes from the fake1234

If this would be available, then we don't need this one: https://github.com/AntelopeIO/spring/issues/490

This tool would improve confidence of no issues on feature activation.

**Comment by arhag** [comment]
We plan to go with https://github.com/AntelopeIO/spring/issues/495 as a medium-term protection instead.
