### ISSUE TITLE
Move get_info from chain_api_plugin to http_plugin

### ISSUE THREAD

**Issue by heifner** [AntelopeIO/spring#506]
As of https://github.com/AntelopeIO/leap/pull/1137 `v1/chain/get_info` has been part of the `node` http category. The `node` category, it is NOT user configurable because it is available for all listened http addresses.

Often users enable `eosio::chain_api_plugin` only so that `v1/chain/get_info` is available.

Move `get_info` to `http_plugin` so that is always available if any API plugin or even just `http_plugin` is enabled. This would enable nodes to be run without having to enable the `eosio::chain_api_plugin` and still have `get_info` available.

**Comment by spoonincode** [comment]
It is strange that `get_info` is on the `node` category, but what's the reasoning for further special-casing it vs just adding it to `chain_ro`?

**Comment by heifner** [comment]
> It is strange that `get_info` is on the `node` category, but what's the reasoning for further special-casing it vs just adding it to `chain_ro`?

The point of it being in `node` category was so it would always be available on all endpoints.

**Comment by heifner** [comment]
Replaced by #515
