### ISSUE TITLE
Test Failure: disaster_recovery_2

### ISSUE THREAD

**Issue by heifner** [AntelopeIO/spring#533]
copied from: https://github.com/AntelopeIO/spring/issues/390#issuecomment-2287117834

> https://github.com/AntelopeIO/spring/actions/runs/10376337986/job/28728623008
> though on an UBSAN build which of course goes kinda on the slow side. Should we reopen this one or do a new issue?

This is a different issue than #390. Not clear what exactly is happening, but certianly not the failure of #390.

```
warn  2024-08-13T20:15:48.591 net-1     net_plugin.cpp:3754           operator()           ] invalid QC claim exception, connection - 7: #136 d67b4e08a8e2bade...: Block includes an invalid QC claim (3030014)
Block state was not found in forkdb for block_num 134. Block number: 136
```

**Comment by bhazzard** [comment]
We haven't seen this fail since August 13th. Closing.
