### ISSUE TITLE
Test proposer policy does not become active when finality has stalled

### ISSUE THREAD

**Issue by arhag** [AntelopeIO/spring#553]
Add an additional libtester test (though using the Savanna cluster testing utility) to test new behavior of https://github.com/AntelopeIO/spring/issues/454.

Create a test where we partition the network (two nodes on one side and two nodes on the other side). Propose a new proposer policy in this scenario and notice that it does not become active. Then reconnect the network and finality should start advancing again and the proposer policy should automatically be promoted to become active.

**Comment by arhag** [comment]
https://github.com/AntelopeIO/spring/issues/380 also resolves this issue.

**Comment by greg7mdp** [comment]
Actually I misread the issue, #582 does not resolve it, will implement the test.
