### ISSUE TITLE
Block extension data available via SHiP but not in ABI

### ISSUE THREAD

**Issue by n8d** [AntelopeIO/spring#720]
It seems we have a new `block_extension` (type 3) in the SHiP stream, but I'm unable to deserialize it because it's not a type that is included in the ABI received on connecting to SHiP.

I'm actually not sure if type 2 is in the ABI as I've not tried to deserialize that one, but in general it seems if data is there we should be able to deserialize it.

**Comment by n8d** [comment]
Yeah it's not been explicit for others, but it's been possible, at least for the extensions I've needed. For example header extension 1 can be deserialized with `producer_authority_schedule`. Typically I will brute force it by trying to deserialize it with every type in the ABI until I find one that looks right, but I'm not having any luck with this one.

That said, I'm not actually sure if block extension 3 has what I need (because I haven't been able to view it). I'm trying to find where the new producer schedules are coming across in savanna blocks (or headers).

**Comment by heifner** [comment]
3 is a `quorum_certificate_extension`
https://github.com/AntelopeIO/spring/blob/5abe003f9c67be8f8e8e792728c4ee68434647e3/libraries/chain/include/eosio/chain/block.hpp#L64-L64
https://github.com/AntelopeIO/spring/blob/5abe003f9c67be8f8e8e792728c4ee68434647e3/libraries/chain/include/eosio/chain/finality/qc.hpp#L77-L77

**Comment by n8d** [comment]
Ok, so not seeing a producer schedule there. If they are not in the original `new_producers`, nor header extension 1, where are they now?

**Comment by greg7mdp** [comment]
In the `finality_extension`, block header extension #2. See `finality_extension.hpp`

**Comment by heifner** [comment]
They are in the block header extension with id 2, `finality_extension`, when they are proposed.

https://github.com/AntelopeIO/spring/blob/9e578e1a13c1f3384edbd91b21488f644a71315f/libraries/chain/include/eosio/chain/finality/finality_extension.hpp#L9-L9

Note it is a diff of the new proposer policy to the old proposer policy. The diff is created by: 

https://github.com/AntelopeIO/spring/blob/9e578e1a13c1f3384edbd91b21488f644a71315f/libraries/libfc/include/fc/container/ordered_diff.hpp#L12-L12

**Comment by n8d** [comment]
Thanks, but now it seems we are back to the original title of the GitHub issue with a different extension. 😆 

I tested every type in the ABI and I'm unable to deserialize block header extension 2.

**Comment by arhag** [comment]
We will add extra types in the SHiP ABI to allow deserializing the block header extension (this is added by https://github.com/AntelopeIO/spring/pull/783). But we decided to not add support for deserializing the block extension because of the problems introduced by the serialization of the dynamic bitset.
