### ISSUE TITLE
P2P: connection monitor running more often than configured

### ISSUE THREAD

**Issue by heifner** [AntelopeIO/spring#830]
With a `connection-cleanup-period = 30` which is the default:

```
info  2024-09-27T13:53:11.169 net-3     net_plugin.cpp:4899           connection_monitor   ] p2p client connections: 0/4, peer connections: 10/10, block producer peers: 0
warn  2024-09-27T13:53:11.224 net-1     net_plugin.cpp:4711           operator()           ] Unable to resolve p2p.bitmars.one:8080 Host not found (authoritative)
info  2024-09-27T13:53:11.318 net-2     net_plugin.cpp:2862           operator()           ] connection failed to peer.eosn.io:9876, Connection refused
info  2024-09-27T13:53:11.445 net-3     net_plugin.cpp:1596           operator()           ] ["p2p.mainnet.eosrio.io:9876 - 259659b" - 6 187.16.79.235:9876] Sending handshake generation 1, lib 396158153, fhead 396158354, id f7b41de76d6e8ef5
warn  2024-09-27T13:53:11.587 net-3     net_plugin.cpp:3608           handle_message       ] ["p2p.mainnet.eosrio.io:9876 - 259659b" - 6 187.16.79.235:9876] Clock offset is 3495269us, calculation: (rec 1727445195011927000 - org 1727445191445814595 + xmt 1727445195011928000 - dst 1727445191587501533)/2
info  2024-09-27T13:53:11.587 net-3     net_plugin.cpp:1596           operator()           ] ["p2p.mainnet.eosrio.io:9876 - 259659b" - 6 187.16.79.235:9876] Sending handshake generation 2, lib 396158153, fhead 396158354, id f7b41de76d6e8ef5
info  2024-09-27T13:53:11.588 net-1     net_plugin.cpp:3465           handle_message       ] ["p2p.mainnet.eosrio.io:9876 - 259659b" - 6 187.16.79.235:9876] Local network version: 9
info  2024-09-27T13:53:11.588 net-1     net_plugin.cpp:2331           recv_handshake       ] ["p2p.mainnet.eosrio.io:9876 - 259659b" - 6 187.16.79.235:9876] handshake lib 396440434, fhead 396440436, id fb0598a488a18012.. sync 1, fhead 396158354, lib 396158153
info  2024-09-27T13:53:12.582 net-2     net_plugin.cpp:3038           operator()           ] ["p2p.mainnet.eosrio.io:9876 - 259659b" - 6 187.16.79.235:9876] Peer closed connection
info  2024-09-27T13:53:12.582 net-2     net_plugin.cpp:3066           operator()           ] ["p2p.mainnet.eosrio.io:9876 - 259659b" - 6 187.16.79.235:9876] Closing connection
info  2024-09-27T13:53:12.582 net-2     net_plugin.cpp:1455           _close               ] ["p2p.mainnet.eosrio.io:9876 - 259659b" - 6 187.16.79.235:9876] closing
info  2024-09-27T13:53:12.682 net-1     net_plugin.cpp:4899           connection_monitor   ] p2p client connections: 0/4, peer connections: 10/10, block producer peers: 0
```

**Comment by luoxiandong** [comment]
I have same problem
`
generation 540, lib 396414235, fhead 396415237, id a3f620c77e66ea08
info  2024-09-27T15:17:34.216 net-1     net_plugin.cpp:4863           connection_monitor   ] p2p client connections: 0/25, peer connections: 34/34, block producer peers: 0
info  2024-09-27T15:17:34.216 net-2     net_plugin.cpp:2833           operator()           ] connection failed to fn001.eossv.org:443, Element not found
info  2024-09-27T15:17:34.216 net-0     net_plugin.cpp:2833           operator()           ] connection failed to node.eosflare.io:1883, Element not found
info  2024-09-27T15:17:34.216 net-0     net_plugin.cpp:2833           operator()           ] connection failed to seed2.greymass.com:9876, Element not found
info  2024-09-27T15:17:34.216 net-1     net_plugin.cpp:2833           operator()           ] connection failed to node1.eoscannon.io:59876, Element not found
info  2024-09-27T15:17:34.216 net-2     net_plugin.cpp:2833           operator()           ] connection failed to publicnode.cypherglass.com:9876, Element not found
info  2024-09-27T15:17:34.216 net-3     net_plugin.cpp:2833           operator()           ] connection failed to bp.eosbeijing.one:8080, Element not found
info  2024-09-27T15:17:34.216 net-0     net_plugin.cpp:2833           operator()           ] connection failed to seed1.greymass.com:9876, Element not found
info  2024-09-27T15:17:34.217 net-1     net_plugin.cpp:1604           operator()           ] ["fullnode.eoslaomao.com:443" - 12 172.67.220.33:443] Sending handshake generation 1, lib 396414235, fhead 396415237, id a3f620c77e66ea08
error 2024-09-27T15:17:34.219 net-3     net_plugin.cpp:2981           operator()           ] ["fullnode.eoslaomao.com:443" - 12 172.67.220.33:443] incoming message length unexpected (1347703880)
info  2024-09-27T15:17:34.219 net-3     net_plugin.cpp:3039           operator()           ] ["fullnode.eoslaomao.com:443" - 12 172.67.220.33:443] Closing connection
info  2024-09-27T15:17:34.219 net-3     net_plugin.cpp:1463           _close               ] ["fullnode.eoslaomao.com:443" - 12 172.67.220.33:443] closing
info  2024-09-27T15:17:34.319 net-0     net_plugin.cpp:4863           connection_monitor   ] p2p client connections: 0/25, peer connections: 34/34, block producer peers: 0
info  2024-09-27T15:17:34.338 net-2     net_plugin.cpp:2308           recv_handshake       ] ["0.0.0.0:9876:blk - 25c26e4" - 5 136.243.72.242:9876] handshake lib 396450196, fhead 396450198, id 55b1631b65ef05a9.. sync 1, fhead 396415237, lib 396414235
info  2024-09-27T15:17:34.338 net-2     net_plugin.cpp:1604           operator()           ] ["0.0.0.0:9876:blk - 25c26e4" - 5 136.243.72.242:9876] Sending handshake generation 601, lib 396414235, fhead 396415237, id a3f620c77e66ea08
info  2024-09-27T15:17:34.468 net-3     net_plugin.cpp:2833           operator()           ] connection failed to peer.eosn.io:9876, Connection refused
info  2024-09-27T15:17:36.774 net-2     net_plugin.cpp:2308           recv_handshake       ] ["p2p.mainnet.eosrio.io:9876:blk - 259659b" - 7 187.16.79.236:9876] handshake lib 396450198, fhead 396450200, id 228effa756dba49f.. sync 1, fhead 396415237, lib 396414235
info  2024-09-27T15:17:36.774 net-2     net_plugin.cpp:1604           operator()           ] ["p2p.mainnet.eosrio.io:9876:blk - 259659b" - 7 187.16.79.236:9876] Sending handshake generation 540, lib 396414235, fhead 396415237, id a3f620c77e66ea08
info  2024-09-27T15:17:37.188 net-0     net_plugin.cpp:2308           recv_handshake       ] ["10.71.87.111:9876:blk - 6af3c99" - 1 3.113.139.0:9876] handshake lib 396450199, fhead 396450201, id b5ecda5c919ff571.. sync 1, fhead 396415237, lib 396414235
info  2024-09-27T15:17:37.188 net-0     net_plugin.cpp:1604           operator()           ] ["10.71.87.111:9876:blk - 6af3c99" - 1 3.113.139.0:9876] Sending handshake generation 68, lib 396414235, fhead 396415237, id a3f620c77e66ea08
info  2024-09-27T15:17:38.837 net-0     net_plugin.cpp:2308           recv_handshake       ] ["p2p.mainnet.eosrio.io:9876:blk - 259659b" - 7 187.16.79.236:9876] handshake lib 396450202, fhead 396450204, id 6aa39130860a844d.. sync 1, fhead 396415237, lib 396414235
info  2024-09-27T15:17:38.837 net-0     net_plugin.cpp:1604           operator()           ] ["p2p.mainnet.eosrio.io:9876:blk - 259659b" - 7 187.16.79.236:9876] Sending handshake generation 541, lib 396414235, fhead 396415237, id a3f620c77e66ea08
info  2024-09-27T15:17:39.379 net-2     net_plugin.cpp:2308           recv_handshake       ] ["94.130.161.135:9876:blk - 2dcf844" - 10 51.77.66.6:9876] handshake lib 396450204, fhead 396450206, id 9376513e11e07c86.. sync 1, fhead 396415237, lib 396414235
info  2024-09-27T15:17:39.379 net-2     net_plugin.cpp:1604           operator()           ] ["94.130.161.135:9876:blk - 2dcf844" - 10 51.77.66.6:9876] Sending handshake generation 544, lib 396414235, fhead 396415237, id a3f620c77e66ea08
info  2024-09-27T15:17:40.545 net-1     net_plugin.cpp:2308           recv_handshake       ] ["tf-eos-mainnet-api-peer1:9876:blk - 41f0256" - 24 51.89.208.163:9876] handshake lib 396450206, fhead 396450208, id 2be6ba025f0b52b4.. sync 1, fhead 396415237, lib 396414235
info  2024-09-27T15:17:40.545 net-1     net_plugin.cpp:1604           operator()           ] ["tf-eos-mainnet-api-peer1:9876:blk - 41f0256" - 24 51.89.208.163:9876] Sending handshake generation 95, lib 396414235, fhead 396415237, id a3f620c77e66ea08
info  2024-09-27T15:17:41.838 net-1     net_plugin.cpp:2308           recv_handshake       ] ["157.90.176.45:9876:blk - 867098b" - 13 157.90.176.45:9876] handshake lib 396450208, fhead 396450210, id 34b2c7cd40b3a83b.. sync 1, fhead 396415237, lib 396414235
info  2024-09-27T15:17:41.838 net-1     net_plugin.cpp:1604           operator()           ] ["157.90.176.45:9876:blk - 867098b" - 13 157.90.176.45:9876] Sending handshake generation 541, lib 396414235, fhead 396415237, id a3f620c77e66ea08
`
Starting from tonight, how fix this problem?

**Comment by luoxiandong** [comment]
> Hopefully we can get a fix in a patch release soon. Until then, remove `fullnode.eoslaomao.com` from your peer list. Keep removing ones that cause the issue.
Can provide some p2p-peer-address list? tks

**Comment by heifner** [comment]
> Can provide some p2p-peer-address list? tks

https://validate.eosnation.io/eos/reports/endpoints.html

**Comment by luoxiandong** [comment]
After the node starts, the RPC is requested to have no response
`curl -x post http://127.0.0.1:8888/v1/chain/get_info`

**Comment by luoxiandong** [comment]
<img width="801" alt="image" src="https://github.com/user-attachments/assets/049d2d72-59ea-48a0-a97d-44e1dc9903aa">
<img width="888" alt="image" src="https://github.com/user-attachments/assets/416ae96e-7fd7-4869-9ca8-b5d7742acf5d">

**Comment by heifner** [comment]
> After the node starts, the RPC is requested to have no response `curl -x post http://127.0.0.1:8888/v1/chain/get_info`

Be very patient with that call. See https://github.com/AntelopeIO/spring/issues/284 and https://github.com/AntelopeIO/spring/issues/527

When syncing `get_info` can take seconds/minutes to respond.

**Comment by heifner** [comment]
Just tested a call to `get_info` while syncing to EOS Mainnet. It took 9 minutes to respond.

**Comment by luoxiandong** [comment]
Yes, the rpc is too long, which will cause our Dapp service to be unavailable. How to improve the RPC call response speed?

**Comment by heifner** [comment]
We plan on doing both #284 and #527 both of which will fix this issue. 
Also when a node is in-sync the repsonse time should be as expected.

**Comment by luoxiandong** [comment]
How long does it take to have a new version?

**Comment by bhazzard** [comment]
> How long does it take to have a new version?

Any date I can provide is a guess. But we're currently targeting this for 1.1.0, which is likely sometime in Q1 2025.
