### ISSUE TITLE
Test failure: nodeos_snapshot_diff_if_test 

### ISSUE THREAD

**Issue by heifner** [AntelopeIO/spring#846]
https://github.com/AntelopeIO/spring/actions/runs/11115558731/job/30884557872

Requested to create a snapshot at block 213, but the node was already at block 217.

**Comment by heifner** [comment]
https://github.com/AntelopeIO/spring/actions/runs/11131513435/job/30933803826

**Comment by linh2931** [comment]
https://github.com/AntelopeIO/spring/actions/runs/11131822845/job/30934996338?pr=850#step:4:1735

**Comment by heifner** [comment]
https://github.com/AntelopeIO/spring/actions/runs/11133200464/job/30939501536

**Comment by greg7mdp** [comment]
https://github.com/AntelopeIO/spring/actions/runs/11133625885/job/30940631902
https://github.com/AntelopeIO/spring/actions/runs/11134937237/job/30944403983

**Comment by spoonincode** [comment]
https://github.com/AntelopeIO/spring/actions/runs/11147253627/job/30982140532

**Comment by spoonincode** [comment]
https://github.com/AntelopeIO/spring/actions/runs/11149293818/job/30988479537

**Comment by spoonincode** [comment]
https://github.com/AntelopeIO/spring/actions/runs/11150390339/job/30991966826

**Comment by spoonincode** [comment]
https://github.com/AntelopeIO/spring/actions/runs/11152694055/job/30999205664
