### ISSUE TITLE
Test failure: distributed-transactions-if-test

### ISSUE THREAD

**Issue by heifner** [AntelopeIO/spring#848]
https://github.com/AntelopeIO/spring/actions/runs/11125907838/job/30915459664

`Duplicate Staring block found: 100 in /__w/spring/spring/build/TestLogs/distributed-transactions-test8/node_bios/stderr.2024_10_01_13_21_16.txt`

Received block 100 late so it restarted speculative block 100. This is expected behavior, so not really sure what we want to do with this. The check was added to guard agaisnt a bug where a block was restarted when it was not suppose to be. Maybe the test should look at the timestamps and only fail if the start block is within some threshold.

**Comment by arhag** [comment]
We can update the test to only fail if a block number is repeated with the same timestamp. It should tolerate repeating a speculative block with a higher timestamp.

**Comment by heifner** [comment]
`build\TestLogs\distributed-transactions-test8\node_bios\stderr.2024_10_01_13_21_16.txt`
```
debug 2024-10-01T13:22:05.393 nodeos    producer_plugin.cpp:2165      start_block          ] Starting block #100 2024-10-01T13:22:06.000 producer defproducerc, deadline 2024-10-01T13:22:05.962
debug 2024-10-01T13:22:06.025 nodeos    producer_plugin.cpp:2165      start_block          ] Starting block #100 2024-10-01T13:22:06.500 producer defproducerc, deadline 2024-10-01T13:22:06.525
debug 2024-10-01T13:22:06.503 nodeos    producer_plugin.cpp:2165      start_block          ] Starting block #100 2024-10-01T13:22:07.000 producer defproducerc, deadline 2024-10-01T13:22:07.003
```
