### ISSUE TITLE
Test failure: p2p_sync_throttle_test

### ISSUE THREAD

**Issue by spoonincode** [AntelopeIO/spring#882]
https://github.com/AntelopeIO/spring/actions/runs/11152149161/job/30997817134

**Comment by spoonincode** [comment]
https://github.com/AntelopeIO/spring/actions/runs/11152694055/job/30999206060

**Comment by greg7mdp** [comment]
https://github.com/AntelopeIO/spring/actions/runs/11165666221/job/31038617077

**Comment by bhazzard** [comment]
Related issue: https://github.com/AntelopeIO/spring/issues/821

**Comment by linh2931** [comment]
https://github.com/AntelopeIO/spring/actions/runs/11170393611/job/31053582839?pr=885#step:4:1274
