### ISSUE TITLE
IF: Document correct process for switching to a backup producer

### ISSUE THREAD

**Issue by ericpassmore** [AntelopeIO/spring#93]
Depends on https://github.com/AntelopeIO/reference-contracts/issues/24 for decision on how finalizers register their keys.

Need to document a new process for switching to backup.

**Comment by arhag** [comment]
See:
https://github.com/eosnetworkfoundation/docs/blob/main/native/60_advanced-topics/20_introduction-finalizers-voting.md
https://github.com/eosnetworkfoundation/docs/blob/main/native/60_advanced-topics/21_managing-finalizer-keys.md
https://github.com/AntelopeIO/spring/wiki/Rotate-Finalizer-Keys

Between these three documents, we cover the intended documentation of this issue.

Improvements and reorganization can be covered in future issues.
