### ISSUE TITLE
[1.1] get_info in irreversible mode (nodeos_irreversible_mode_if_lr_test)

### ISSUE THREAD

**Issue by heifner** [AntelopeIO/spring#935]
Before #920, a node running in `irreversible` mode would always report the same value for:
```
"head_block_num":456
"last_irreversible_block_num":456
```

Now it is possible for a node running in `irreversible` mode to return different values:
```
"head_block_num":457
"last_irreversible_block_num":456
```

See test failure: https://github.com/AntelopeIO/spring/actions/runs/11349047274/job/31565035139

This is possible now because `accepted_block` is signaled before `irreversible_block` and a `get_info` call can come in between those two signals. Before since the `get_info` ran on the main thread, it could not execute between the two signals.

**Comment by linh2931** [comment]
https://github.com/AntelopeIO/spring/actions/runs/11367787258/job/31622083125?pr=941#step:4:1332
