### ISSUE TITLE
nodeos_block_num metric flapping on BP node

### ISSUE THREAD

**Issue by ank-everstake** [AntelopeIO/spring#956]
#### Describe the bug
`nodeos_block_num` Prometheus metric is showing **0** when block producer is producing a block itself. 
It generates false-positive alerts and renders Grafana charts unreadable. Non-producer nodes are not affected.

#### Expected behavior
Show real block number even if node is currently producing without flapping.

#### Screenshots
![2024-10-21_10-37](https://github.com/user-attachments/assets/afaaa38a-6b4e-4606-a043-13910acd9b47)

![2024-10-18_00-19](https://github.com/user-attachments/assets/31dca5f8-0525-4e35-bb7f-a5102c076ab7)
Left side - producer logs, right side is showing `while true curl | grep nodeos_block_num`

#### Specs / Additional context
OS - Ubuntu 22.04 LTS
RAM - 256 GB
CPU - AMD Ryzen Threadripper 7960X

We observe this issue **starting from** 
```   
v1.0.0-a8159feae6f7f0d89dc0f990682a3b09635a3e1f
```
it **persists** on current version
```
v1.0.1-574650744460373f635d48cac9aa6dee67dcbfdb
```

**Comment by heifner** [comment]
Note: #707
