### ISSUE TITLE
Proposal for better handling of non-final "poison" blocks

### ISSUE THREAD

**Issue by bhazzard** [AntelopeIO/spring#987]
When a node hangs on a long-running transaction and can't apply a block, the node should give up trying to apply the block if it is not finalized. Ideally this would automatically handle potential scenarios where a block contains a transaction with infinite execution time without manual intervention like starting from a snapshot.

To be decided:
- duration to wait before giving up
- what to do if the block later is finalized

**Comment by heifner** [comment]
https://hackmd.io/fLWy5YaXT2WJWgsWknQYvg

**Comment by bhazzard** [comment]
Reviewed and moving forward
