### ISSUE TITLE
Test failure: plugin_http_api_test

### ISSUE THREAD

**Issue by linh2931** [AntelopeIO/spring#992]
https://github.com/AntelopeIO/spring/actions/runs/11594759334/job/32282588256

```
Errors while running CTest
1/1 Test #2201: plugin_http_api_test .............***Timeout  50.03 sec
```

**Comment by bhazzard** [comment]
Analyze logs to determine cause.

**Comment by linh2931** [comment]
@heifner Would the fix be restore the producer configuration to the default after
https://github.com/AntelopeIO/spring/blob/0f038c82a3fc47ac84a3b8df9d992f0cb46e5a1e/tests/plugin_http_api_test.py#L954-L960
and move the pause and resume at the end of producer api test?

**Comment by heifner** [comment]
> @heifner Would the fix be restore the producer configuration to the default after

Yes, I think so.
